In [80]:
import numpy as np
import pandas as pd
# Read acsv file
# Check the first five rows of dataframe

data = pd.read_csv('data/data.csv', index_col=5, parse_dates=['Date'])
data.head()

,Position,Track Name,Artist,Streams,URL,Region
Date,,,,,,
2017-01-01,1,Reggaetón Lento (Bailemos),CNCO,19272,https://open.spotify.com/track/3AEZUABDXNtecAO...,ec
2017-01-01,2,Chantaje,Shakira,19270,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,ec
2017-01-01,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,https://open.spotify.com/track/3QwBODjSEzelZyV...,ec
2017-01-01,4,Vente Pa' Ca,Ricky Martin,14954,https://open.spotify.com/track/7DM4BPaS7uofFul...,ec
2017-01-01,5,Safari,J Balvin,14269,https://open.spotify.com/track/6rQSrBHf7HlZjtc...,ec

In [81]:
data_global = data[data['Region'] == 'global']
groupby_tracks =  data_global.groupby(['Date','Track Name','Artist']).sum()[['Streams']].reset_index()
top10_global = groupby_tracks.sort_values(by=['Streams'], ascending=False)
top_global = top10_global.drop_duplicates(['Track Name']).reset_index(drop=True)

In [83]:
# Patch the top50 global dataset

top50_global = groupby_tracks.sort_values(by=['Streams'], ascending=False)
top50_global = top50_global.drop_duplicates(['Track Name']).reset_index(drop=True).head(50)
top50_global.head()

        Date                          Track Name        Artist   Streams
0 2017-05-27  Despacito (Featuring Daddy Yankee)    Luis Fonsi  11381520
1 2017-03-03                        Shape of You    Ed Sheeran   9891056
2 2017-05-26                   Despacito - Remix    Luis Fonsi   8525474
3 2017-12-24     All I Want for Christmas Is You  Mariah Carey   8069105
4 2017-08-25            Look What You Made Me Do  Taylor Swift   7908492

In [84]:
# Count amount of the top50 tracks

all_top50_artists = top_global.loc[top_global['Artist'].isin(top50_global['Artist'])]
num_50tracks=  all_top50_artists.groupby(['Artist']).count()[['Track Name']]
total_50tracks_count = num_50tracks.rename(columns={'Track Name':'Total Tracks'})
top50_tracks_count = top50_global.groupby(['Artist']).count()[['Track Name']]
top50_tracks_count = top50_tracks_count.rename(columns={'Track Name':'top50_tracks_count'})
count_50table= top50_tracks_count.merge(total_50tracks_count,on=('Artist'))

count_50table.head()

                top50_tracks_count  Total Tracks
Artist
Ariana Grande                    1             6
Band Aid                         1             1
Brenda Lee                       1             2
Calvin Harris                    1            12
Camila Cabello                   1             8

In [74]:
# Add the total of streams in top50

top50_total_streams = top50_global.groupby(['Artist']).sum()[['Streams']]
modify_top50_total_streams = top50_total_streams.rename(columns={'Streams':'top50_total_streams'})
count_50table = count_50table.merge(modify_top50_total_streams,on=('Artist'))
count_50table

                  top50_tracks_count  Total Tracks  top50_total_streams
Artist
Ariana Grande                      1             6              3710487
Band Aid                           1             1              3919169
Brenda Lee                         1             2              3589792
Calvin Harris                      1            12              3499197
Camila Cabello                     1             8              4949898
Chris Rea                          1             1              3584428
DJ Khaled                          2            11             10855102
David Guetta                       1             5              4419676
Drake                              4            29             17336101
Dua Lipa                           1             4              4497944
Ed Sheeran                         5            31             28168731
Eminem                             1            22              4495842
French Montana                     1             3              3744979
Future                             1            30              3730661
J Balvin                           1             7              4967261
John Lennon                        1             1              3652828
Justin Bieber                      1             5              4053188
Kendrick Lamar                     7            17             31099628
Kygo                               1             6              4639832
Luis Fonsi                         2             3             19906994
Mariah Carey                       1             1              8069105
Maroon 5                           1            10              3535745
Michael Bublé                      1             8              4183203
Post Malone                        1             6              7156650
Sam Smith                          2            19              8624205
Selena Gomez                       2             4              7584410
Taylor Swift                       2            14             11490217
The Chainsmokers                   2            17              9160229
The Weeknd                         1            13              3747787
Wham!                              1             1              6485447
ZAYN                               1             4              4595854

In [85]:
# def Z_ScoreNormalization(x):
# for x in top50_total_streams:
#     x = float(x - top50_total_streams.mean())/top50_total_streams.std()
#     print(x)
top50_total_streams_norm = (top50_total_streams - top50_total_streams.min()) / (top50_total_streams.max() - top50_total_streams.min())
top50_total_streams_norm

                   Streams
Artist
Ariana Grande     0.007655
Band Aid          0.015216
Brenda Lee        0.003282
Calvin Harris     0.000000
Camila Cabello    0.052561
Chris Rea         0.003088
DJ Khaled         0.266514
David Guetta      0.033350
Drake             0.501329
Dua Lipa          0.036186
Ed Sheeran        0.893810
Eminem            0.036110
French Montana    0.008905
Future            0.008386
J Balvin          0.053190
John Lennon       0.005566
Justin Bieber     0.020072
Kendrick Lamar    1.000000
Kygo              0.041327
Luis Fonsi        0.594476
Mariah Carey      0.165574
Maroon 5          0.001324
Michael Bublé     0.024782
Post Malone       0.132514
Sam Smith         0.185686
Selena Gomez      0.148013
Taylor Swift      0.289525
The Chainsmokers  0.205107
The Weeknd        0.009007
Wham!             0.108196
ZAYN              0.039733

In [86]:
# Add the total of streams in top50

# top50_total_streams = top50_global.groupby(['Artist']).sum()[['Streams']]
modify_top50_total_streams = top50_total_streams_norm.rename(columns={'Streams':'top50_total_streams'})
count_50table = count_50table.merge(modify_top50_total_streams,on=('Artist'))
count_50table

                  top50_tracks_count  Total Tracks  top50_total_streams
Artist
Ariana Grande                      1             6             0.007655
Band Aid                           1             1             0.015216
Brenda Lee                         1             2             0.003282
Calvin Harris                      1            12             0.000000
Camila Cabello                     1             8             0.052561
Chris Rea                          1             1             0.003088
DJ Khaled                          2            11             0.266514
David Guetta                       1             5             0.033350
Drake                              4            29             0.501329
Dua Lipa                           1             4             0.036186
Ed Sheeran                         5            31             0.893810
Eminem                             1            22             0.036110
French Montana                     1             3             0.008905
Future                             1            30             0.008386
J Balvin                           1             7             0.053190
John Lennon                        1             1             0.005566
Justin Bieber                      1             5             0.020072
Kendrick Lamar                     7            17             1.000000
Kygo                               1             6             0.041327
Luis Fonsi                         2             3             0.594476
Mariah Carey                       1             1             0.165574
Maroon 5                           1            10             0.001324
Michael Bublé                      1             8             0.024782
Post Malone                        1             6             0.132514
Sam Smith                          2            19             0.185686
Selena Gomez                       2             4             0.148013
Taylor Swift                       2            14             0.289525
The Chainsmokers                   2            17             0.205107
The Weeknd                         1            13             0.009007
Wham!                              1             1             0.108196
ZAYN                               1             4             0.039733

In [88]:
# install sklearn and statsmodels packages
from sklearn import linear_model
import tkinter as tk
import statsmodels.api as sm
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt

X = count_50table[['Total Tracks', 'top50_total_streams']]
Y = count_50table['top50_tracks_count']

# use sklearn to make regression
regr = linear_model.LinearRegression()
regr.fit(X, Y)

print ('Intercept: \n', regr.intercept_)
print ('Coefficients: \n', regr.coef_)

# by using statsmodels
# add a constant value X
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
predictions = model.predict(X)

# add tkinter GUI for the task
root = tk.Tk()
root.title('Multiple Linear Regression')

canvas1 = tk.Canvas(root, width=1300, height=420)
canvas1.pack()

intercept_result = ('Intercept: ', regr.intercept_)
label_intercept = tk.Label(root, text=intercept_result, justify = 'center')
canvas1.create_window(260, 270, window=label_intercept)

coefficients_result = ('Coefficients: ', regr.coef_)
label_coefficients = tk.Label(root, text=coefficients_result, justify = 'center')
canvas1.create_window(260, 290, window=label_coefficients)

# add model salary to roght side of the UI
print_model = model.summary()
label_model = tk.Label(root, text=print_model, justify = 'center')
canvas1.create_window(800, 270, window=label_model)

# add totoal tracks and top50_total_streams labels and input boxes
label_tracks = tk.Label(root, text='Input Total Tracks: ')
canvas1.create_window(100, 150, window=label_tracks)
# create tracks entry box
entry_tracks = tk.Entry(root)
canvas1.create_window(350, 150, window=entry_tracks)

label_streams = tk.Label(root, text='Input Top50 Total Streams(millions): ')
canvas1.create_window(140, 200, window=label_streams)
# create tracks entry box
entry_streams = tk.Entry(root)
canvas1.create_window(350, 200, window=entry_streams)

def values(): 
    global Total_Tracks 
    #our 1st input variable
    Total_Tracks = float(entry_tracks.get()) 
    
    global Top50_Total_Streams 
    #our 2nd input variable
    Top50_Total_Streams = float(entry_streams.get()) 
    
    Prediction_result  = ('Predicted Top50 Tracks Count: ', regr.predict([[Total_Tracks ,Top50_Total_Streams]]))
    label_Prediction = tk.Label(root, text= Prediction_result, bg='orange')
    canvas1.create_window(260, 360, window=label_Prediction)
    
button_submit = tk.Button (root, text='Predicted Top50 Tracks Count',command=values, bg='orange') 
# button to call the 'values' command above 
canvas1.create_window(270, 240, window=button_submit)

#plot 1st scatter 
figure_tracks = plt.Figure(figsize=(5,4), dpi=100)
ax_tracks = figure_tracks.add_subplot(111)
ax_tracks.scatter(count_50table['Total Tracks'].astype(float),count_50table['top50_tracks_count'].astype(float), color = 'r')
scatter_tracks = FigureCanvasTkAgg(figure_tracks, root) 
scatter_tracks.get_tk_widget().pack(side=tk.RIGHT, fill=tk.BOTH)
ax_tracks.legend() 
ax_tracks.set_xlabel('Total Tracks')
ax_tracks.set_title('Total Tracks Vs. Top50 Tracks Count')

#plot 2nd scatter 
figure_streams = plt.Figure(figsize=(5,4), dpi=100)
ax_streams = figure_streams.add_subplot(111)
ax_streams.scatter(count_50table['top50_total_streams'].astype(float),count_50table['top50_tracks_count'].astype(float), color = 'g')
scatter_streams = FigureCanvasTkAgg(figure_streams, root) 
scatter_streams.get_tk_widget().pack(side=tk.RIGHT, fill=tk.BOTH)
ax_streams.legend() 
ax_streams.set_xlabel('Top50 Total Streams')
ax_streams.set_title('Top50 Total Streams Vs. Top50 Tracks Count')
 

root.mainloop()
# need to pop the window to view the GUI frame

Intercept:
 0.6866650567950541
Coefficients:
 [0.01946219 4.67341507]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)